### ISSUE TITLE
Leere Projekttabelle

### ISSUE THREAD

**Issue by ThoEJ** [phoeuia/prse#213]
Wenn man in der tabellarischen Übersicht ein Projekt auswählt, einen Aufgabenbereich auswählt und dann eine Aufgabe auswählt, dann auf Aktivität hinzufügen geht und diesen Dialog dann abbricht und danach auf Projekt hinzufügen geht und diesen Dialog dann ebenfalls abbricht, dann verschwinden die Daten in der Projekttabelle.

**Comment by cupcake0137** [comment]
Nach dem man diese Schritte ausgeführt hat (nach dem verschwinden der Daten in der Projekttabelle) und dann auf
- "tabellarisch" geht, verschwindet dann die gesamte Übersicht und von all den Buttons die noch sichtbar sind, funktioniert nur der Button "Personenverwaltung"
- "graphisch" geht, verschwindet dann auch wieder gesamte Übersicht und es taucht oben links ein graues Rechteck auf, und alle sichtbaren Buttons funktionieren außer "Zeiterfassung" und "Menü"

**Comment by phoeuia** [comment]
Bug gefixed, daher wird das Issue geschlossen.

**Comment by cupcake0137** [comment]
Wenn man ein Projekt, einen Aufgabenbereich und anschließend unter Aufgabenbereich auf "Hinzufügen" und dann auf "Abbrechen" geht, gehen die Daten der Projekte wieder verloren.

Fehlermeldungen:
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at tmatt.model.TaskDomain.getFinishedTasks(TaskDomain.java:288)
	at tmatt.model.Project.getFinishedTasks(Project.java:391)
	at tmatt.model.Project.progressProperty(Project.java:319)
	at tmatt.view.ProjectOverviewController.lambda$1(ProjectOverviewController.java:123)
	at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:578)
	at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:563)
	at javafx.scene.control.TableCell.updateItem(TableCell.java:644)
	at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.requestCellUpdate(TableRowSkinBase.java:659)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.handleControlPropertyChanged(TableRowSkinBase.java:234)
	at com.sun.javafx.scene.control.skin.TableRowSkin.handleControlPropertyChanged(TableRowSkin.java:70)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197)
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:72)
	at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:115)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1797)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1879)
	at com.sun.javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2528)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1189)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at tmatt.model.TaskDomain.getFinishedTasks(TaskDomain.java:288)
	at tmatt.model.Project.getFinishedTasks(Project.java:391)
	at tmatt.model.Project.progressProperty(Project.java:319)
	at tmatt.view.ProjectOverviewController.lambda$1(ProjectOverviewController.java:123)
	at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:578)
	at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:563)
	at javafx.scene.control.TableCell.updateItem(TableCell.java:644)
	at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.requestCellUpdate(TableRowSkinBase.java:659)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.lambda$init$497(TableRowSkinBase.java:159)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.control.Cell.setItem(Cell.java:403)
	at javafx.scene.control.Cell.updateItem(Cell.java:670)
	at javafx.scene.control.TableRow.updateItem(TableRow.java:259)
	at javafx.scene.control.TableRow.indexChanged(TableRow.java:225)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1797)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1879)
	at com.sun.javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2528)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1189)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at tmatt.model.TaskDomain.getFinishedTasks(TaskDomain.java:288)
	at tmatt.model.Project.getFinishedTasks(Project.java:391)
	at tmatt.model.Project.progressProperty(Project.java:319)
	at tmatt.view.ProjectOverviewController.lambda$1(ProjectOverviewController.java:123)
	at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:578)
	at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:563)
	at javafx.scene.control.TableCell.updateItem(TableCell.java:644)
	at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:533)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.checkState(TableRowSkinBase.java:634)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(TableRowSkinBase.java:571)
	at javafx.scene.control.Control.computePrefHeight(Control.java:547)
	at javafx.scene.Parent.prefHeight(Parent.java:935)
	at javafx.scene.layout.Region.prefHeight(Region.java:1435)
	at com.sun.javafx.scene.control.skin.VirtualFlow.resizeCellSize(VirtualFlow.java:1947)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1798)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1879)
	at com.sun.javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2528)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1189)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

**Comment by phoeuia** [comment]
Fehler sollte jetzt endgültig behoben sein
